function Xefp = DifFK_UR10_3(in1,in2)
%DIFFK_UR10_3
%    XEFP = DIFFK_UR10_3(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    21-Feb-2018 21:13:19

% Xp = J(q) * qp
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q1p = in2(1,:);
q2p = in2(2,:);
q3p = in2(3,:);
Xefp = [q1p.*(cos(q1).*2.561e-1+sin(q1).*sin(q2).*6.127e-1-cos(q2).*sin(q1).*sin(q3).*6.873e-1+cos(q3).*sin(q1).*sin(q2).*6.873e-1)-q2p.*cos(q1).*(cos(q2-q3).*6.873e-1+cos(q2).*6.127e-1)+q3p.*cos(q2-q3).*cos(q1).*6.873e-1;q1p.*(sin(q1).*2.561e-1-cos(q1).*sin(q2).*6.127e-1+cos(q1).*cos(q2).*sin(q3).*6.873e-1-cos(q1).*cos(q3).*sin(q2).*6.873e-1)-q2p.*sin(q1).*(cos(q2-q3).*6.873e-1+cos(q2).*6.127e-1)+q3p.*cos(q2-q3).*sin(q1).*6.873e-1;q3p.*sin(q2-q3).*6.873e-1-q2p.*(sin(q2-q3).*6.873e-1+sin(q2).*6.127e-1);sin(q1).*(q2p-q3p);-cos(q1).*(q2p-q3p);q1p];
