function Xef = FK_UR10_3(in1)
%FK_UR10_3
%    XEF = FK_UR10_3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    21-Feb-2018 21:13:19

% x = f(q)
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
Xef = [sin(q1).*2.561e-1-cos(q1).*sin(q2).*6.127e-1+cos(q1).*cos(q2).*sin(q3).*6.873e-1-cos(q1).*cos(q3).*sin(q2).*6.873e-1;cos(q1).*(-2.561e-1)-sin(q1).*sin(q2).*6.127e-1+cos(q2).*sin(q1).*sin(q3).*6.873e-1-cos(q3).*sin(q1).*sin(q2).*6.873e-1;cos(q2-q3).*6.873e-1+cos(q2).*6.127e-1;angle(-sin(q2-q3).*(cos(q1)+sin(q1).*1i));angle(cos(q2-q3).*-1i+sqrt(-cos(q2-q3).^2+1.0));pi.*sign(sin(q2-q3)).*(-1.0./2.0)];
