function [H0_W,H1_W,H2_W,H3_W] = H_UR10_3(in1)
%H_UR10_3
%    [H0_W,H1_W,H2_W,H3_W] = H_UR10_3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    21-Feb-2018 21:13:19

%Compute Transformation Matrices: H(q)
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
H0_W = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.6e1./1.25e2,1.0],[4,4]);
if nargout > 1
    H1_W = reshape([cos(q1),sin(q1),0.0,0.0,0.0,0.0,1.0,0.0,sin(q1),-cos(q1),0.0,0.0,0.0,0.0,1.6e1./1.25e2,1.0],[4,4]);
end
if nargout > 2
    H2_W = reshape([-cos(q1).*sin(q2),-sin(q1).*sin(q2),cos(q2),0.0,cos(q1).*cos(q2),cos(q2).*sin(q1),sin(q2),0.0,-sin(q1),cos(q1),0.0,0.0,cos(q1).*sin(q2).*(-6.127e-1),sin(q1).*sin(q2).*(-6.127e-1),cos(q2).*6.127e-1+1.6e1./1.25e2,1.0],[4,4]);
end
if nargout > 3
    H3_W = reshape([cos(q1).*cos(q2).*sin(q3)-cos(q1).*cos(q3).*sin(q2),cos(q2).*sin(q1).*sin(q3)-cos(q3).*sin(q1).*sin(q2),cos(q2).*cos(q3)+sin(q2).*sin(q3),0.0,-cos(q1).*cos(q2).*cos(q3)-cos(q1).*sin(q2).*sin(q3),-sin(q1).*sin(q2).*sin(q3)-cos(q2).*cos(q3).*sin(q1),cos(q2).*sin(q3)-cos(q3).*sin(q2),0.0,sin(q1),-cos(q1),0.0,0.0,sin(q1).*2.561e-1-cos(q1).*sin(q2).*6.127e-1+cos(q1).*cos(q2).*sin(q3).*6.873e-1-cos(q1).*cos(q3).*sin(q2).*6.873e-1,cos(q1).*(-2.561e-1)-sin(q1).*sin(q2).*6.127e-1+cos(q2).*sin(q1).*sin(q3).*6.873e-1-cos(q3).*sin(q1).*sin(q2).*6.873e-1,cos(q2).*6.127e-1+cos(q2).*cos(q3).*6.873e-1+sin(q2).*sin(q3).*6.873e-1+1.6e1./1.25e2,1.0],[4,4]);
end
