function [H1_0,H2_0,H3_0,Hcm1_0,Hcm2_0,Hcm3_0] = H(in1)
%H
%    [H1_0,H2_0,H3_0,HCM1_0,HCM2_0,HCM3_0] = H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    22-Feb-2018 01:05:18

%Compute Transformation Matrices: H(q)
q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
H1_0 = reshape([cos(q1),sin(q1),0.0,0.0,0.0,0.0,1.0,0.0,sin(q1),-cos(q1),0.0,0.0,0.0,0.0,1.273e-1,1.0],[4,4]);
if nargout > 1
    H2_0 = reshape([-cos(q1).*cos(q2),-cos(q2).*sin(q1),-sin(q2),0.0,cos(q1).*sin(q2),sin(q1).*sin(q2),-cos(q2),0.0,sin(q1),-cos(q1),0.0,0.0,cos(q1).*cos(q2).*(-6.127e-1),cos(q2).*sin(q1).*(-6.127e-1),sin(q2).*(-6.127e-1)+1.273e-1,1.0],[4,4]);
end
if nargout > 2
    H3_0 = reshape([-cos(q2+q3).*cos(q1),-cos(q2+q3).*sin(q1),-sin(q2+q3),0.0,sin(q2+q3).*cos(q1),sin(q2+q3).*sin(q1),-cos(q2+q3),0.0,sin(q1),-cos(q1),0.0,0.0,sin(q1).*2.561e-1-cos(q1).*cos(q2).*6.127e-1-cos(q1).*cos(q2).*cos(q3).*6.873e-1+cos(q1).*sin(q2).*sin(q3).*6.873e-1,cos(q1).*(-2.561e-1)-cos(q2).*sin(q1).*6.127e-1+sin(q1).*sin(q2).*sin(q3).*6.873e-1-cos(q2).*cos(q3).*sin(q1).*6.873e-1,sin(q2+q3).*(-6.873e-1)-sin(q2).*6.127e-1+1.273e-1,1.0],[4,4]);
end
if nargout > 3
    Hcm1_0 = reshape([cos(q1),sin(q1),0.0,0.0,-sin(q1),cos(q1),0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0./1.0e1,1.0],[4,4]);
end
if nargout > 4
    Hcm2_0 = reshape([-cos(q1).*cos(q2),-cos(q2).*sin(q1),-sin(q2),0.0,cos(q1).*sin(q2),sin(q1).*sin(q2),-cos(q2),0.0,sin(q1),-cos(q1),0.0,0.0,sin(q1).*(3.0./2.0e1)-cos(q1).*cos(q2).*3.0635e-1,cos(q1).*(-3.0./2.0e1)-cos(q2).*sin(q1).*3.0635e-1,sin(q2).*(-3.0635e-1)+1.273e-1,1.0],[4,4]);
end
if nargout > 5
    Hcm3_0 = reshape([-cos(q2+q3).*cos(q1),-cos(q2+q3).*sin(q1),-sin(q2+q3),0.0,sin(q2+q3).*cos(q1),sin(q2+q3).*sin(q1),-cos(q2+q3),0.0,sin(q1),-cos(q1),0.0,0.0,sin(q1).*(1.0./1.0e2)-cos(q1).*cos(q2).*6.127e-1-cos(q1).*cos(q2).*cos(q3).*3.437e-1+cos(q1).*sin(q2).*sin(q3).*3.437e-1,cos(q1).*(-1.0./1.0e2)-cos(q2).*sin(q1).*6.127e-1+sin(q1).*sin(q2).*sin(q3).*3.437e-1-cos(q2).*cos(q3).*sin(q1).*3.437e-1,sin(q2+q3).*(-3.437e-1)-sin(q2).*6.127e-1+1.273e-1,1.0],[4,4]);
end
