function Xcm2 = fcm2(in1)
%FCM2
%    XCM2 = FCM2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    21-Feb-2018 18:37:11

% ForwarKinematics xcm2 = fcm2(q)
q1 = in1(1,:);
q2 = in1(2,:);
Xcm2 = [cos(q1).*(2.9e1./2.5e2)-sin(q1).*(q2+2.3e1./8.0e1);sin(q1).*(2.9e1./2.5e2)+cos(q1).*(q2+2.3e1./8.0e1);0.0;angle(cos(q1)+sin(q1).*1i);0.0;pi.*(-1.0./2.0)];
