function J_cm2_0 = Jcm2(in1)
%JCM2
%    J_CM2_0 = JCM2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    21-Feb-2018 18:37:12

% Jacobian: Jcm2(q)
q1 = in1(1,:);
q2 = in1(2,:);
J_cm2_0 = reshape([sin(q1).*(-2.9e1./2.5e2)-cos(q1).*(q2+2.3e1./8.0e1),cos(q1).*(2.9e1./2.5e2)-sin(q1).*(q2+2.3e1./8.0e1),0.0,0.0,0.0,1.0,-sin(q1),cos(q1),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,4]);
