function [M,Md,C,g] = dynamic_model(in1)
%DYNAMIC_MODEL
%    [M,MD,C,G] = DYNAMIC_MODEL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Dec-2017 12:53:12

T1 = in1(:,17);
T2 = in1(:,18);
g = in1(:,22);
k1 = in1(:,13);
k2 = in1(:,14);
k3 = in1(:,15);
l2 = in1(:,8);
l3 = in1(:,9);
m1 = in1(:,10);
m2 = in1(:,11);
m3 = in1(:,12);
q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
qd2 = in1(:,5);
qd3 = in1(:,6);
z0 = in1(:,16);
t2 = sin(q2);
t3 = q2+q3;
t4 = sin(t3);
t10 = l3.*m3.*t4;
t5 = -t10-l2.*m2.*t2-l2.*m3.*t2;
t6 = l2.^2;
t7 = l3.^2;
t8 = m3.*t7;
t9 = cos(q3);
t11 = l2.*l3.*m3.*t9;
t12 = t8+t11;
M = reshape([m1+m2+m3,t5,-t10,t5,t8+m2.*t6+m3.*t6+l2.*l3.*m3.*t9.*2.0,t12,-l3.*m3.*t4,t12,t8],[3,3]);
if nargout > 1
    t13 = cos(q2);
    t14 = cos(t3);
    t15 = l2.*m2.*t13;
    t16 = l2.*m3.*t13;
    t17 = l3.*m3.*t14;
    t18 = t15+t16+t17;
    t22 = l3.*m3.*qd3.*t14;
    t19 = -t22-qd2.*t18;
    t20 = sin(q3);
    t21 = qd2+qd3;
    Md = reshape([0.0,t19,-l3.*m3.*t14.*t21,t19,l2.*l3.*m3.*qd3.*t20.*-2.0,-l2.*l3.*m3.*qd3.*t20,-l3.*m3.*t14.*t21,-l2.*l3.*m3.*qd3.*t20,0.0],[3,3]);
end
if nargout > 2
    C = reshape([0.0,0.0,0.0,-t22-l2.*m2.*qd2.*t13-l2.*m3.*qd2.*t13-l3.*m3.*qd2.*t14,-l2.*l3.*m3.*qd3.*t20,l2.*l3.*m3.*qd2.*t20,-t22-l3.*m3.*qd2.*t14,-l2.*l3.*m3.*qd2.*t20-l2.*l3.*m3.*qd3.*t20,0.0],[3,3]);
end
if nargout > 3
    t23 = g.*l3.*m3.*t4;
    g = [-g.*m1-g.*m2-g.*m3+k1.*q1-k1.*z0;t23-T1.*k2+k2.*q2+g.*l2.*m2.*t2+g.*l2.*m3.*t2;t23-T2.*k3+k3.*q3];
end
